import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import '../../public/sass/base/helper.scss';
import '../../public/sass/base/reset.scss';

import { Geist } from 'next/font/google';

const geistSans = Geist({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'LMS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        {children}
      </body>
    </html>
  );
}
